# yaml-language-server: $schema=https://json-schema.axonivy.com/app/12.0.0/variables.json
# == Variables ==
Variables:
  google-translate-connector:
    # The google translate api key
    # [password]
    apiKey: ''
